project:
  type: website
  execute-dir: project
  output-dir: docs
  render: 
    - "*.qmd"

website:
  title: "Cavazos Personal Slide Template"
  navbar:
    right:
      - icon: github
        href: https://github.com/bcavazos/teach_quarto-slides
        aria-label: GitHub

  sidebar:
    style: "docked"
    alignment: left
    border: true
    collapse-level: 2
    contents:
      - test: "Home"
        href: index.qmd
  page-footer:
    center: "&copy; 2026, Brittany Cavazos"

execute:
  freeze: auto

format:
  html:
    code-overflow: wrap
    code-line-numbers: false
    code-copy: hover
    toc: true
    theme:
      light: cavazos-light.scss
      dark: cavazos-dark.scss
    link-external-newwindow: true
    link-external-icon: false
  